# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kotlin-libraries:
        patterns:
          - "org.jetbrains.kotlin:kotlin-stdlib:kotlin"
          - "org.jetbrains.kotlin:kotlin-android:kotlin"
          - "org.jetbrains.kotlin:kotlin-gradle-plugin:kotlin"
          - "org.jetbrains.kotlin:kotlin-allopen:kotlin"
          - "com.google.devtools.ksp:ksp"
    open-pull-requests-limit: 5
